
import { ClinicalRecord, SharedRecord, RecordStatus, PrivacyLevel, DisclosureTiming } from './types';

export const MY_CLINIC_NAME = "Apex Physio & Sports";

// Records belonging to the user (candidates for sharing)
export const MY_PATIENT_RECORDS: ClinicalRecord[] = [
  {
    id: 'p-001',
    patientName: 'Sarah Jenkins',
    patientId: 'P-9021',
    dateOfBirth: '1989-05-12',
    age: 34,
    gender: 'F',
    diagnosis: 'Rotator Cuff Tendinopathy',
    diagnosisCategory: 'Shoulder',
    icd10: 'M75.11',
    treatmentDate: '2023-10-15',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'Private',
    fundingCaseId: 'PVT-99821',
    subjectiveComplaint: 'Sharp pain with overhead reaching (7/10). Dull ache at night.',
    objectiveFindings: 'ROM: Flexion 145°, Abduction 130°. Empty Can Test: Positive. Hawkins-Kennedy: Positive.',
    promScores: 'SPADI: 62/100 (Initial) -> 18/100 (Discharge).',
    treatmentPlan: 'Manual therapy, progressive loading, home exercise program.',
    outcome: 'Full recovery. Return to recreational tennis.',
    detailedNotes: 'Week 1-2: Pain reduction focus. Week 3-4: Loading introduced. Patient responded well to eccentric loading protocol.',
    clinicalReasoning: 'Initial presentation suggested impingement, but manual tests confirmed tendinopathy. Adjusted plan to focus on tendon capacity.',
    sessions: 12,
    durationWeeks: 6,
    raw: {
      subjective: 'Pt c/o R shldr pn (7/10) w/ overhead activity. "Catching" sensation noted. Night pn ++. Aggravating: reaching, putting on coat.',
      objective: 'Obs: R scap winging. AROM: Flex 145, Abd 130 w/ pn arc. PROM: WNL. Str: Abd 4/5, ER 4-/5. Spec Tests: (+) Hawkins, (+) Empty Can, (-) Speed\'s.',
      treatment: 'Mobs: Gr III AP glides. STM: Upper Trap/Levator. Ex: Scap iso, IR/ER t-band (light). Edu: Load mgmt, avoid OH < 2wks.',
      proms: 'SPADI: 62 (Pain 65, Disab 58).',
      notes: 'Wk 1-2: Pn reduction focus. Wk 3-4: Loading intro. Pt responded well to eccentric load.'
    }
  },
  {
    id: 'p-002',
    patientName: 'Michael Chen',
    patientId: 'P-9022',
    dateOfBirth: '1995-08-23',
    age: 28,
    gender: 'M',
    diagnosis: 'ACL Reconstruction Rehab',
    diagnosisCategory: 'Knee',
    icd10: 'S83.51',
    treatmentDate: '2023-09-01',
    status: RecordStatus.ONGOING,
    fundingSource: 'Private',
    fundingCaseId: 'PVT-77213',
    subjectiveComplaint: 'Instability sensation prior to surgery. Post-op pain managed well.',
    objectiveFindings: 'Post-op Day 14. Extension deficit 5°. Flexion 90°. Quad lag present.',
    promScores: 'IKDC: 45.2. Lysholm Score: 55.',
    treatmentPlan: 'Standard ACL protocol. Focus on extension and quad activation.',
    outcome: 'Progression on track. Running initiated at week 12.',
    detailedNotes: 'Patient struggled with quad activation initially. Used NMES for 3 weeks.',
    clinicalReasoning: 'Delayed running initiation due to minor effusion at week 10.',
    sessions: 24,
    durationWeeks: 16,
    raw: {
      subjective: 'Pre-op: c/o instability. Post-op (D14): Pn 2/10, mostly stiff AM. Swelling decr.',
      objective: 'Stitches removed. Incision clean. Effusion: 1+. AROM: Ext -5 (lag), Flex 90. Quad set: Poor recruitment.',
      treatment: 'NMES to VMO 20mins. Patella mobs. Heel slides, quad sets, SLR (w/ brace). Gait trng: WBAT w/ crutches.',
      proms: 'IKDC: 45.2. Lysholm: 55.',
      notes: 'Pt struggled w/ quad activation initially. Used NMES x3 wks.'
    }
  },
  {
    id: 'p-003',
    patientName: 'Emma Thompson',
    patientId: 'P-9023',
    dateOfBirth: '1978-11-04',
    age: 45,
    gender: 'F',
    diagnosis: 'Chronic Low Back Pain',
    diagnosisCategory: 'Spine',
    icd10: 'M54.5',
    treatmentDate: '2023-11-05',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'EPC',
    fundingCaseId: 'EPC-1092-22',
    subjectiveComplaint: 'Intermittent central LBP for 3 years. Worse with sitting >30mins.',
    objectiveFindings: 'ROM: Flexion 50% limited. Extension full but painful. Centralization with repeated extension.',
    promScores: 'Oswestry Disability Index (ODI): 42% -> 12%.',
    treatmentPlan: 'McKenzie Method, core stability.',
    outcome: 'Significantly Improved. Self-management effective.',
    detailedNotes: 'Directional preference for extension established early.',
    clinicalReasoning: 'Mechanical origin confirmed via repeated movements.',
    sessions: 8,
    durationWeeks: 5,
    raw: {
      subjective: 'LBP central, intermittent 3yrs. Agg: Sitting > 30m. Ease: Walking. No radicular sx.',
      objective: 'Post: Incr lordosis. ROM: Flex 50% (fingertip-knee), Ext full/painful @ EOR. Rep Mvmt: Rep Ext reduces central pn (centralization).',
      treatment: 'McKenzie Ext protocol (10x/2hrs). Postural edu (lumbar roll). Core: TA activation.',
      proms: 'ODI: 42% (Mod Disability).',
      notes: 'Directional pref for ext established early.'
    }
  },
  {
    id: 'p-004',
    patientName: 'David Wilson',
    patientId: 'P-9024',
    dateOfBirth: '1961-03-15',
    age: 62,
    gender: 'M',
    diagnosis: 'Total Knee Arthroplasty',
    diagnosisCategory: 'Knee',
    icd10: 'Z96.651',
    treatmentDate: '2023-10-20',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'DVA',
    fundingCaseId: 'DVA-GOLD-991',
    subjectiveComplaint: 'Post-op stiffness and swelling.',
    objectiveFindings: '2 weeks post-op. ROM 5-95. Gait: Antalgic.',
    promScores: 'KOOS: 62% at discharge.',
    treatmentPlan: 'Gait training, ROM, strengthening.',
    outcome: 'Discharged with ROM 0-125.',
    detailedNotes: 'Scar mobilization performed at week 4 due to adhesions.',
    clinicalReasoning: 'Aggressive ROM needed early to prevent stiffness.',
    sessions: 15,
    durationWeeks: 8,
    raw: {
      subjective: '2wks post TKA (R). "Tight band" feeling. Pn 4/10 at rest, 8/10 w/ mvmt.',
      objective: 'Obs: Mod swelling/bruising. ROM: AROM 5-95. Ext lag 5. Gait: Antalgic, decr stance time R.',
      treatment: 'Bike (rocking for ROM). Scar mob (gentle). STS training. Step-ups (low).',
      proms: 'KOOS: 62% at DC.',
      notes: 'Scar mob @ wk 4 d/t adhesions.'
    }
  },
  {
    id: 'p-005',
    patientName: 'Lisa Rodriguez',
    patientId: 'P-9025',
    dateOfBirth: '2001-07-30',
    age: 22,
    gender: 'F',
    diagnosis: 'Lateral Ankle Sprain (Grade II)',
    diagnosisCategory: 'Ankle',
    icd10: 'S93.4',
    treatmentDate: '2023-12-01',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'Workcover',
    fundingCaseId: 'WC-NSW-8821',
    subjectiveComplaint: 'Rolled ankle playing soccer. Cannot weight bear comfortably.',
    objectiveFindings: 'Swelling ++ lateral aspect. Anterior Drawer +ve. Talar Tilt -ve.',
    promScores: 'FAAM-Sport: 25% -> 95%.',
    treatmentPlan: 'RICE, bracing, proprioception.',
    outcome: 'Return to sport at 4 weeks.',
    detailedNotes: 'Early mobilization strategy adopted.',
    clinicalReasoning: 'Avoided prolonged immobilization to reduce stiffness.',
    sessions: 6,
    durationWeeks: 4,
    raw: {
      subjective: 'Inv injury soccer 2d ago. Pop heard. Lat ankle pn 8/10. WB difficult.',
      objective: 'Obs: Lat malleolus swelling ++. Palp: ATFL ++, CFL +. AROM: DF restricted. ST: (+) Ant Drawer, (-) Talar Tilt.',
      treatment: 'RICE. Boot fitted. Crutches x 3d. Iso ev/inv (pain free).',
      proms: 'FAAM-Sport: 25%.',
      notes: 'Early mob strategy adopted.'
    }
  },
  // --- New Patients Added Below ---
  {
    id: 'p-006',
    patientName: 'Robert Geller',
    patientId: 'P-9026',
    dateOfBirth: '1965-02-12',
    age: 58,
    gender: 'M',
    diagnosis: 'Tennis Elbow (Lateral Epicondylalgia)',
    diagnosisCategory: 'Elbow/Hand',
    icd10: 'M77.11',
    treatmentDate: '2024-01-10',
    status: RecordStatus.ONGOING,
    fundingSource: 'Private',
    subjectiveComplaint: 'Lateral elbow pain, aggravated by gripping and typing.',
    objectiveFindings: 'Pain with resisted wrist extension (Cozen\'s test). Grip strength reduced 20% compared to left.',
    promScores: 'PRTEE: 52/100.',
    treatmentPlan: 'Isometric holds, eccentric wrist extension, ergonomic review.',
    outcome: 'Improving, pain free grip increasing.',
    detailedNotes: 'Patient works in IT, high typing load. Ergonomic mouse recommended.',
    clinicalReasoning: 'Tendinopathy confirmed. Load management is primary intervention.',
    sessions: 5,
    durationWeeks: 3,
    raw: {
      subjective: 'R lat elbow pn. 6 months duration. Worse w/ coffee cup, typing.',
      objective: 'TTP Lat Epi. (+) Cozen, (+) Maudsley. Grip str: R 30kg, L 42kg.',
      treatment: 'Isometrics 45s x 5. MWM Lat glide. Taping.',
      proms: 'PRTEE: 52.',
      notes: 'Ergo mouse ordered.'
    }
  },
  {
    id: 'p-007',
    patientName: 'Anita Singh',
    patientId: 'P-9027',
    dateOfBirth: '1998-11-20',
    age: 25,
    gender: 'F',
    diagnosis: 'Cervicogenic Headache',
    diagnosisCategory: 'Head/Neck',
    icd10: 'G44.82',
    treatmentDate: '2023-11-15',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'Private',
    subjectiveComplaint: 'Unilateral headaches starting from neck base, radiating to eye.',
    objectiveFindings: 'C1/2 rotation restricted (Flexion-Rotation Test positive). Suboccipital tenderness.',
    promScores: 'NDI: 28% -> 4%.',
    treatmentPlan: 'SNAGs C1/2, deep neck flexor training, posture.',
    outcome: 'Resolved. No headaches for 4 weeks.',
    detailedNotes: ' responded immediately to C1/2 SNAG.',
    clinicalReasoning: 'Upper cervical dysfunction driving headache symptoms.',
    sessions: 6,
    durationWeeks: 5,
    raw: {
      subjective: 'R sided HA. "Ram\'s horn" pattern. Desk worker.',
      objective: 'FRT: R 25deg (hard end feel), L 45deg. PA: C2/3 stiff/painful.',
      treatment: 'Mulligan SNAG C1/2. DNF chin tucks. Scap setting.',
      proms: 'NDI: 28%.',
      notes: 'Rapid responder.'
    }
  },
  {
    id: 'p-008',
    patientName: 'Lucas Davies',
    patientId: 'P-9028',
    dateOfBirth: '2012-07-08',
    age: 11,
    gender: 'M',
    diagnosis: 'Osgood-Schlatter Disease',
    diagnosisCategory: 'Pediatric',
    icd10: 'M92.5',
    treatmentDate: '2023-09-10',
    status: RecordStatus.ONGOING,
    fundingSource: 'Private',
    subjectiveComplaint: 'Knee pain below kneecap after soccer.',
    objectiveFindings: 'Prominent tibial tuberosity. TTP. Tight quads.',
    promScores: 'VAS: 6/10 post sport.',
    treatmentPlan: 'Load management (reduce training volume), quad stretching, foam rolling.',
    outcome: 'Managing well, playing with minimal pain.',
    detailedNotes: 'Growth spurt recently.',
    clinicalReasoning: 'Apophysitis due to rapid growth and high load.',
    sessions: 4,
    durationWeeks: 8,
    raw: {
      subjective: 'L knee bump painful. Soccer 4x/week.',
      objective: 'Tib Tuberosity swollen/TTP. Ely\'s test: Tight rectus.',
      treatment: 'Edu: It\'s growing pains/load related. Reduced training to 2x/wk.',
      proms: 'VAS 6/10.',
      notes: 'Parents reassured.'
    }
  },
  {
    id: 'p-009',
    patientName: 'Grace Kim',
    patientId: 'P-9029',
    dateOfBirth: '1950-03-30',
    age: 73,
    gender: 'F',
    diagnosis: 'Distal Radius Fracture (Post-Cast)',
    diagnosisCategory: 'Elbow/Hand',
    icd10: 'S52.5',
    treatmentDate: '2023-12-05',
    status: RecordStatus.ONGOING,
    fundingSource: 'Private',
    subjectiveComplaint: 'Stiffness, fear of movement.',
    objectiveFindings: 'Wrist Ext 20, Flex 15. Supination limited.',
    promScores: 'PRWE: 75/100.',
    treatmentPlan: 'AAROM, oedema management, dart thrower\'s motion.',
    outcome: 'ROM slowly improving.',
    detailedNotes: 'CRPS precautionary measures taken (desensitization).',
    clinicalReasoning: 'Prevent stiffness is priority.',
    sessions: 8,
    durationWeeks: 4,
    raw: {
      subjective: 'Cast off yesterday. Scared to move.',
      objective: 'Swollen ++. stiff. ROM limited global.',
      treatment: 'Wax bath. Gentle PROM. Tendon glides.',
      proms: 'PRWE 75.',
      notes: 'Monitor for CRPS.'
    }
  },
  {
    id: 'p-010',
    patientName: 'Samuel O\'Connor',
    patientId: 'P-9030',
    dateOfBirth: '1985-09-12',
    age: 38,
    gender: 'M',
    diagnosis: 'Lumbar Disc Herniation (L5/S1)',
    diagnosisCategory: 'Spine',
    icd10: 'M51.17',
    treatmentDate: '2023-10-01',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'Workcover',
    fundingCaseId: 'WC-VIC-1102',
    subjectiveComplaint: 'Back pain with S1 radiculopathy (calf/heel).',
    objectiveFindings: 'SLR +ve at 40 deg. Absent ankle jerk.',
    promScores: 'Roland Morris: 18/24 -> 4/24.',
    treatmentPlan: 'Neural mobilization, extension bias, core control.',
    outcome: 'returned to work full duties.',
    detailedNotes: 'Leg pain centralized after 3 weeks.',
    clinicalReasoning: 'Radiculopathy responding to conservative care.',
    sessions: 14,
    durationWeeks: 10,
    raw: {
      subjective: 'Electric shock down L leg to heel. Cant tie shoes.',
      objective: 'Shift to R. SLR (+) L 40deg. S1 reflex nil.',
      treatment: 'Ext in lying. Sliders. Tape.',
      proms: 'RMDQ 18.',
      notes: 'Refer for MRI if no change 2wks.'
    }
  }
];

// Network records (available to browse)
export const NETWORK_RECORDS: SharedRecord[] = [
  {
    id: 'net-001',
    patientName: 'James Peterson',
    patientId: 'P-X882',
    dateOfBirth: '1992-02-14',
    age: 31,
    gender: 'M',
    diagnosis: 'Achilles Tendinopathy',
    diagnosisCategory: 'Ankle',
    icd10: 'M76.6',
    treatmentDate: '2023-08-15', // Older than 30 days
    status: RecordStatus.DISCHARGED,
    fundingSource: 'Private',
    subjectiveComplaint: 'Morning stiffness in heel. Pain during running warm-up.',
    objectiveFindings: 'Thickening of mid-portion Achilles. Tenderness on palpation.',
    promScores: 'VISA-A: 45 -> 88.',
    treatmentPlan: 'Alfredson Protocol.',
    outcome: 'Returned to running.',
    detailedNotes: 'Pain spiked at week 3, reduced load temporarily.',
    clinicalReasoning: 'Classic overuse pattern. Load management was key.',
    sessions: 14,
    durationWeeks: 12,
    sharedByClinic: 'Metro Sports Physio',
    sharedDate: '2023-11-01',
    privacyLevel: PrivacyLevel.FULL,
    disclosureTiming: DisclosureTiming.DELAYED,
    tier: 'Gold',
    distanceKm: 3.2,
    rating: 5
  },
  {
    id: 'net-002',
    patientName: 'Linda Marcus',
    patientId: 'P-Y221',
    dateOfBirth: '1968-09-22',
    age: 55,
    gender: 'F',
    diagnosis: 'Frozen Shoulder (Adhesive Capsulitis)',
    diagnosisCategory: 'Shoulder',
    icd10: 'M75.0',
    treatmentDate: '2023-12-10', // Recent
    status: RecordStatus.ONGOING,
    fundingSource: 'Private',
    subjectiveComplaint: 'Severe pain at night. Cannot reach behind back.',
    objectiveFindings: 'Stage 2 (Freezing). ER restricted to 10°. Flexion 80°.',
    promScores: 'SPADI: 78/100.',
    treatmentPlan: 'Pain management, gentle mobilization.',
    outcome: 'Progression to thawing stage.',
    detailedNotes: 'Intra-articular injection referred at week 4.',
    clinicalReasoning: 'Conservative management failed initially.',
    sessions: 10,
    durationWeeks: 8,
    sharedByClinic: 'Northside Rehab',
    sharedDate: '2023-12-15',
    privacyLevel: PrivacyLevel.SUMMARY, // Summary only
    disclosureTiming: DisclosureTiming.IMMEDIATE,
    tier: 'Silver',
    distanceKm: 12.5,
    rating: 4
  },
  {
    id: 'net-003',
    patientName: 'Marcus Johnson',
    patientId: 'P-Z991',
    dateOfBirth: '2004-05-18',
    age: 19,
    gender: 'M',
    diagnosis: 'Hamstring Strain (Grade II)',
    diagnosisCategory: 'Hip/Thigh',
    icd10: 'S76.3',
    treatmentDate: '2023-09-20',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'EPC',
    fundingCaseId: 'EPC-1002',
    subjectiveComplaint: 'Sudden sharp pain while sprinting.',
    objectiveFindings: 'Pain on resisted knee flexion. Palpable defect mid-belly.',
    promScores: 'LEFS: 40/80 -> 78/80.',
    treatmentPlan: 'Askling protocol (L-protocol).',
    outcome: 'RTS at 5 weeks with no recurrence.',
    detailedNotes: 'Lengthening exercises emphasized.',
    clinicalReasoning: 'Focus on eccentric strength at long muscle lengths.',
    sessions: 8,
    durationWeeks: 6,
    sharedByClinic: 'Elite Performance Center',
    sharedDate: '2023-10-01',
    privacyLevel: PrivacyLevel.FULL,
    disclosureTiming: DisclosureTiming.DELAYED,
    tier: 'Gold',
    distanceKm: 8.1,
    rating: 5
  },
  {
    id: 'net-004',
    patientName: 'Patricia Davis',
    patientId: 'P-A123',
    dateOfBirth: '1982-11-30',
    age: 41,
    gender: 'F',
    diagnosis: 'Cervical Radiculopathy',
    diagnosisCategory: 'Spine',
    icd10: 'M54.12',
    treatmentDate: '2023-11-20',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'Workcover',
    fundingCaseId: 'WC-99221',
    subjectiveComplaint: 'Neck pain radiating to right arm/thumb.',
    objectiveFindings: 'Positive Spurling\'s test. C6 dermatome paresthesia. Reflexes diminished.',
    promScores: 'NDI: 38% -> 8%.',
    treatmentPlan: 'Traction, neural glides, posture correction.',
    outcome: 'Symptoms resolved centrally.',
    detailedNotes: 'Mechanical traction provided significant relief.',
    clinicalReasoning: 'Discogenic origin suspected.',
    sessions: 10,
    durationWeeks: 6,
    sharedByClinic: 'City Central Physio',
    sharedDate: '2023-12-05',
    privacyLevel: PrivacyLevel.FULL,
    disclosureTiming: DisclosureTiming.DELAYED, // Recent + Delayed = Hidden notes
    tier: 'Bronze',
    distanceKm: 1.5,
    rating: 3
  },
   {
    id: 'net-005',
    patientName: 'Robert Wilson',
    patientId: 'P-B456',
    dateOfBirth: '1955-04-10',
    age: 68,
    gender: 'M',
    diagnosis: 'Hip Osteoarthritis',
    diagnosisCategory: 'Hip/Thigh',
    icd10: 'M16.1',
    treatmentDate: '2023-07-10',
    status: RecordStatus.ONGOING,
    fundingSource: 'DVA',
    subjectiveComplaint: 'Stiff in mornings. Groin pain after walking >1km.',
    objectiveFindings: 'Limited IR (15°). Positive FABER test.',
    promScores: 'Harris Hip Score: 55 -> 72.',
    treatmentPlan: 'GLA:D Program.',
    outcome: 'Improved function, surgery delayed.',
    detailedNotes: 'Group classes very effective for adherence.',
    clinicalReasoning: 'Education and neuromuscular control focus.',
    sessions: 12,
    durationWeeks: 12,
    sharedByClinic: 'Community Health',
    sharedDate: '2023-08-01',
    privacyLevel: PrivacyLevel.FULL,
    disclosureTiming: DisclosureTiming.IMMEDIATE,
    tier: 'Silver',
    distanceKm: 5.0,
    rating: 4
  },
  // --- New Network Records Added Below ---
  {
    id: 'net-006',
    patientName: 'George Miller',
    patientId: 'P-C789',
    dateOfBirth: '1948-06-15',
    age: 75,
    gender: 'M',
    diagnosis: 'Post-Stroke Hemiparesis',
    diagnosisCategory: 'Neurology',
    icd10: 'I69.351',
    treatmentDate: '2023-09-01',
    status: RecordStatus.ONGOING,
    fundingSource: 'NDIS',
    subjectiveComplaint: 'Difficulty walking and using right hand.',
    objectiveFindings: 'R sided weakness (3/5). Increased tone R calf (Modified Ashworth 2).',
    promScores: 'Berg Balance: 35/56 -> 42/56.',
    treatmentPlan: 'Gait re-education, Task specific training upper limb.',
    outcome: 'Mobility improving, needs aid.',
    detailedNotes: 'Focus on sit-to-stand transfers and weight shifting.',
    clinicalReasoning: 'Neuroplasticity principles applied high repetition.',
    sessions: 25,
    durationWeeks: 16,
    sharedByClinic: 'NeuroMotion Rehab',
    sharedDate: '2023-11-20',
    privacyLevel: PrivacyLevel.FULL,
    disclosureTiming: DisclosureTiming.IMMEDIATE,
    tier: 'Gold',
    distanceKm: 8.5,
    rating: 5
  },
  {
    id: 'net-007',
    patientName: 'Emily Clark',
    patientId: 'P-D012',
    dateOfBirth: '1980-01-25',
    age: 44,
    gender: 'F',
    diagnosis: 'BPPV (Benign Paroxysmal Positional Vertigo)',
    diagnosisCategory: 'Vestibular',
    icd10: 'H81.1',
    treatmentDate: '2023-10-30',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'Private',
    subjectiveComplaint: 'Room spins when rolling over in bed.',
    objectiveFindings: 'Positive Dix-Hallpike R (Rotary Nystagmus).',
    promScores: 'DHI: 52 -> 0.',
    treatmentPlan: 'Epley Maneuver.',
    outcome: 'Resolved after 2 sessions.',
    detailedNotes: 'Nausea managed well.',
    clinicalReasoning: 'Canalithiasis of Posterior Canal.',
    sessions: 2,
    durationWeeks: 1,
    sharedByClinic: 'Balance & Dizzy Centre',
    sharedDate: '2023-11-05',
    privacyLevel: PrivacyLevel.FULL,
    disclosureTiming: DisclosureTiming.IMMEDIATE,
    tier: 'Silver',
    distanceKm: 20.0,
    rating: 5
  },
  {
    id: 'net-008',
    patientName: 'Harry Potters',
    patientId: 'P-E345',
    dateOfBirth: '1995-07-31',
    age: 28,
    gender: 'M',
    diagnosis: 'Carpal Tunnel Syndrome',
    diagnosisCategory: 'Elbow/Hand',
    icd10: 'G56.0',
    treatmentDate: '2023-08-20',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'Workcover',
    fundingCaseId: 'WC-QLD-441',
    subjectiveComplaint: 'Numbness in thumb/index finger at night.',
    objectiveFindings: 'Phalen\'s test positive 30s. Weak APB.',
    promScores: 'Boston CTQ: 3.2 -> 1.5.',
    treatmentPlan: 'Splinting, tendon gliding, nerve sliders.',
    outcome: 'Symptoms manageable without surgery.',
    detailedNotes: 'Night splint was crucial.',
    clinicalReasoning: 'Compression neuropathy managed conservatively.',
    sessions: 6,
    durationWeeks: 6,
    sharedByClinic: 'Hand Therapy Plus',
    sharedDate: '2023-10-15',
    privacyLevel: PrivacyLevel.SUMMARY,
    disclosureTiming: DisclosureTiming.DELAYED,
    tier: 'Bronze',
    distanceKm: 4.2,
    rating: 3
  },
  {
    id: 'net-009',
    patientName: 'Sophie Turner',
    patientId: 'P-F678',
    dateOfBirth: '1990-05-15',
    age: 33,
    gender: 'F',
    diagnosis: 'Post-Partum Pelvic Girdle Pain',
    diagnosisCategory: 'Pelvic Health',
    icd10: 'O26.7',
    treatmentDate: '2023-09-15',
    status: RecordStatus.DISCHARGED,
    fundingSource: 'Private',
    subjectiveComplaint: 'Pain in SIJ area walking > 10mins.',
    objectiveFindings: 'Positive P4 test, Active SLR difficult.',
    promScores: 'PGQ: 45 -> 10.',
    treatmentPlan: 'Compression belt, glute strengthening, stabilization.',
    outcome: 'Return to full function.',
    detailedNotes: 'Belt weaned off at week 4.',
    clinicalReasoning: 'Instability component post-birth.',
    sessions: 5,
    durationWeeks: 8,
    sharedByClinic: 'Women\'s Wellness Physio',
    sharedDate: '2023-11-10',
    privacyLevel: PrivacyLevel.FULL,
    disclosureTiming: DisclosureTiming.DELAYED,
    tier: 'Gold',
    distanceKm: 6.0,
    rating: 5
  },
  {
    id: 'net-010',
    patientName: 'Arthur Dent',
    patientId: 'P-G901',
    dateOfBirth: '1980-03-11',
    age: 43,
    gender: 'M',
    diagnosis: 'Plantar Fasciitis',
    diagnosisCategory: 'Ankle',
    icd10: 'M72.2',
    treatmentDate: '2023-07-01',
    status: RecordStatus.ONGOING,
    fundingSource: 'Private',
    subjectiveComplaint: 'First step pain in morning. Sharp heel pain.',
    objectiveFindings: 'TTP medial calcaneal tubercle. Tight calves.',
    promScores: 'FAAM: 65 -> 80.',
    treatmentPlan: 'Shockwave, stretching, orthotics.',
    outcome: 'Slow improvement.',
    detailedNotes: 'Shockwave x3 sessions helpful.',
    clinicalReasoning: 'Chronic degenerative change.',
    sessions: 8,
    durationWeeks: 12,
    sharedByClinic: 'Foot Focus',
    sharedDate: '2023-10-01',
    privacyLevel: PrivacyLevel.FULL,
    disclosureTiming: DisclosureTiming.IMMEDIATE,
    tier: 'Silver',
    distanceKm: 2.5,
    rating: 4
  }
];

// Mock data for Global Search (patients NOT yet shared)
export const MOCK_GLOBAL_INDEX = [
  {
    id: 'gl-001',
    patientName: 'Thomas Anderson',
    dateOfBirth: '1975-03-11',
    clinicName: 'Matrix Health',
    location: 'Westside'
  },
  {
    id: 'gl-002',
    patientName: 'Sarah Connor',
    dateOfBirth: '1984-05-12',
    clinicName: 'Skynet Rehab',
    location: 'Downtown'
  },
  {
    id: 'gl-003',
    patientName: 'Bruce Wayne',
    dateOfBirth: '1980-02-19',
    clinicName: 'Gotham Physio',
    location: 'East End'
  },
  {
    id: 'gl-004',
    patientName: 'Diana Prince',
    dateOfBirth: '1990-10-21',
    clinicName: 'Themyscira Sports Med',
    location: 'Island District'
  },
  {
    id: 'gl-005',
    patientName: 'Clark Kent',
    dateOfBirth: '1988-06-18',
    clinicName: 'Metropolis Health',
    location: 'Central'
  }
];
